language: elixir
elixir:
- 1.8.2
otp_release:
- '22.0'
addons:
  postgresql: '9.4'
services:
- postgresql
before_script:
- mix do ecto.create, ecto.migrate
script:
- MIX_ENV=test mix coveralls.travis
deploy:
  provider: heroku
  api_key:
    secure: dBnv5JdjAlYlvSKrY8samEKR03fYju4l4aF3hJZhN5N86HaYYHAUn4Bo6Z32BdWtLMiPuzciqjpSHZcCNQgIyyJrSqXPYZWOqOLg/lMaNLCvqEfiRiEYXo6gRehgrKERHlYZZpCf22zHCIAaVU10iPpbBXBTrPUSpclwczSizVOlgoc6b+UtgrNf3QbJpraCbu/plhSfx74ZBx8TrCDfKv5FsplrRgaLi4dsTOCFBSqVoPrZtO0UdOn045Y/aDxTXwGG1kwjGkBZvtj5mvTox9m0dF0vc65Sh/QjJt86f2Q1m715suoB0Z2RfKUZdIjKFFrQ+TmJrlLRWUSurSEnZSpLpfWiO/vmxLvYchE3PFe0xy1kKgNxWu/Q7Ldh6iCIHbx6EpoJnqSC7iv0IiLqrbFM/q7GKJL/fdKQh/dFrGOrdjfqPVc+VjVpoGezRHqn0Q85+ntu9l24kvPxgyoNalrYcM/B9xXaNO8NcVVo53ppOFw13cXBbIGkTrAMkCe70JdI6vJ0mVa56dd0VZvy1TQxDzmicbXb40q4rsDi2Y2urYiinu9Mtl6E7tGIJvNmzVH2ahTo0mn835n6Rgdtp1EHkf4aN+L5+OQXNu4au2VdjYI0L+9Bnh0ksiXD0f8syfar/RgT3VGUyEj6cMJqZDbBpWnsAxppdMf/Gon9EYY=
  app: mockatron
notifications:
  slack:
    secure: dtdEUraINHVG+Y5VwlzdzML3HoJijwC4kUFyiZxvJGMC+TJDCxSW9i2X4R+NvTfMTsmX4iLJ7PPWKn+iKYSHabEKQ9ZIybzPbAaFWyQez07ZECzWoNr/tF8qBRNFq70F7TTLwIoxjG8Do7QwLVgHMJp8mhn6WIQZjtqmPF3o5lqDFG7cCs/+k6soBsPsKKmWs839wjTpDeM894BcHac5HchosFRWiES3Oh0KjMfgbU0uxvzy6cLicya0qtvS9rM+aocIdZmv/EYepIVdLNpoiApzD8ovuE4mzewJrM3AUw5J7FUcD2Km2q9bj9EPEwBf4ilVjhuAgkLVdnU/sASN3TjzVlK2wj1TY+kq95ahrd2XYlxoqIwjHK5Ix3OpOXCayMwZ62s/wBrMpdPq7XyxsAbv9t0tX4D+opBy8OWar+D9j8tEvdTK3Ntb+r3xSbj9qi/gWTItk/sdMKoJzvo0fvu1sw/fe6RAKzybqFM3MrzV2ymMRo0ZfggqucYJfIAysojPRZSZSdLhpAEXlEDTnTB3LjRLCXdgxIT84FnpPXsf4JFjitMziingaZfJvhPd40rZlbS+Xhd013fG/feqxx9EPwqiA3EJU9hM1ldvRModDK/Z3WblKzPY8UcKdMgwefk1aphNwXiQSGyV6iDpbSetuESe+ZrQxqVhR1GRDOk=
