on:
  push:
    tags:
      - '*'
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    name: Mockatron Test (OTP 24.1 / Elixir 1.12.3)
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.12.3
      - name: Get Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MIX_ENV: test
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy to Gigalixir
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: main # Check out main instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.1
      - name: Deploy Application
        uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_APP: mockatron
          GIGALIXIR_CLEAN: true
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false
