on:
  push:
    tags:
      - '*'
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP 24.1 / Elixir 1.12.3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.12.3
      - run: mix deps.get
      - run: mix coveralls.github
